/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mnolan' at '05/10/16 14:02' with Gradle 2.14.1
 *
 * @author mnolan, @date 05/10/16 14:02
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
