/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class JFrogShimmerApi {
	
	public JFrogShimmerApi() {
		
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
}
