/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class JFrogCustomerApp {
	
	public JFrogCustomerApp() {
		JFrogShimmerApi api = new JFrogShimmerApi();
		System.out.println(api.someLibraryMethod());
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String[] args) {
    	new JFrogCustomerApp();
    }
}
