/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Harith' at '4/26/24 9:39 AM' with Gradle 2.14.1
 *
 * @author Harith, @date 4/26/24 9:39 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
